# Generated by Django 5.2 on 2025-05-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Captain', 'Captain'), ('Referee', 'Referee'), ('Guest', 'Guest')], default='Guest', max_length=20),
        ),
    ]
