# Generated by Django 5.2 on 2025-05-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('captain', 'Captain'), ('referee', 'Referee'), ('guest', 'Guest')], default='guest', max_length=20),
        ),
    ]
